---
- name: Install packages
  apt:
    pkg:
    - msmtp
    update_cache: true
  tags:
  - install

- name: Copy .msmtprc configuration file
  template:
    src: templates/msmtprc.j2
    dest: "{{ msmtp_config_file_path }}"
    group: "{{ msmtp_config_file_group }}"
    mode: "{{ msmtp_config_file_mode }}"
    owner: "{{ msmtp_config_file_owner }}"
  tags:
  - configure
